# Generated by Django 4.1.6 on 2023-02-01 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BIT_Clubs', '0002_alter_club_display_picture_alter_club_header_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='display_picture',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='club',
            name='header_image',
            field=models.ImageField(upload_to=''),
        ),
    ]
